/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'salekuma' at '8/25/16 12:48 PM' with Gradle 3.0
 *
 * @author salekuma, @date 8/25/16 12:48 PM
 */
public class Library {
	  public static void main(String args[]){
		   System.out.println("Hi Hi");
    }
}
